# Generated by Django 3.2.8 on 2021-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
