# Generated by Django 3.2.8 on 2021-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
